### ISSUE TITLE
Definir possíveis temas para o projeto

### ISSUE THREAD

**Issue by GeiseSaunier** [GeiseSaunier/Autizando#1]
**Descrição**
A ideia dessa issue é listar temas e problemas.

**Objetivo**
Definir o tema para o projeto. Analisar o problema e pensar em soluções usando ferramentas computacionais.

**Tarefas**
- [x] Fazer um brainstorming com os possíveis temas;
- [x] Listar o problema;
- [x] Pensar em uma solução;

**Checklist**
- [x] Tema definido;
- [x] Problema encontrado;
- [x] Solução definida;

**Comment by GeiseSaunier** [comment]
@IanoMaciel, nós já discutimos sobre os possíveis temas para o projeto e já definimos um, então irei fechar essa issue. Tudo bem pra você? Deseja acrescentar algo?

**Comment by IanoMaciel** [comment]
@GeiseSaunier, estou de acordo com o tema escolhido. Acredito que podemos finalizar essa issue e trabalhar no desenvolvimento da próxima.

**Comment by GeiseSaunier** [comment]
Ok! Issue finalizada de acordo com os critérios de aceitação.
