### ISSUE TITLE
Desenvolvimento da Tela de Login

### ISSUE THREAD

**Issue by GeiseSaunier** [GeiseSaunier/Autizando#3]
**Descrição**
A ideia dessa issue é dar início ao desenvolvimento do aplicativo Autizando.

**Objetivo**
Desenvolver a Tela de Login.

**Tarefas**
- [x] Criar componente para dados do usuário;
- [x] Criar componente para senha;
- [x] Inserir especificações para a tela de Login;

**Checklist**
- [x] Componentes criados;
- [x] Especificações inseridas;

**Critérios de aceitação**
- [x] A equipe está de acordo com as implementações;

**Comment by IanoMaciel** [comment]
@GeiseSaunier, estamos com problema na barra de navegação da tela de login. E agora?

**Comment by GeiseSaunier** [comment]
@IanoMaciel , qual problema especificamente?

**Comment by IanoMaciel** [comment]
Na imagem abaixo é possível identificar a aba citada no comentário anterior.  
![image](https://user-images.githubusercontent.com/71051791/131593684-d19d0b05-f1f4-4ece-bda2-8caaa77eaf57.png)

**Comment by GeiseSaunier** [comment]
@IanoMaciel, você quer tirar o Tela de Login escrito em preto no canto superior esquerdo?

**Comment by IanoMaciel** [comment]
@GeiseSaunier , isso mesmo. Se encontrar algo relacionado, disponibilize o link aqui, por gentileza.

**Comment by GeiseSaunier** [comment]
@IanoMaciel , olha só: encontrei um link aqui, acho que pode ajudar. É este: https://stackoverflow.com/questions/45639304/block-disable-tabs-in-tabnavigator-react-navigation
Espero que ajude. Qualquer coisa, me mantenha informada, por favor.

**Comment by IanoMaciel** [comment]
@GeiseSaunier , ok!

**Comment by GeiseSaunier** [comment]
Tela finalizada!
