### ISSUE TITLE
Desenvolvimento Tela de Cadastro

### ISSUE THREAD

**Issue by GeiseSaunier** [GeiseSaunier/Autizando#4]
**Descrição**
A ideia dessa issue é desenvolver mais algumas features para o aplicativo Autizando.

**Objetivo**
Desenvolver a Tela de cadastro.

**Tarefas**
- [x] Criar componente para dados do usuário;
- [x] Inserir especificações para a tela de Cadastro;

**Checklist**
- [x] Componentes criados;
- [x] Especificações inseridas;

**Critérios de aceitação**
- [x] A equipe está de acordo com as implementações;

**Comment by IanoMaciel** [comment]
@GeiseSaunier, estou dificuldades com o button radio. Após clicar no elemento eu não consigo desmarcar.

**Comment by IanoMaciel** [comment]
Issue finalizada. Falta apenas inserir o logo da aplicação, porém, estamos aguardado o retorno da designer.
