### ISSUE TITLE
Página de recuperação de senha

### ISSUE THREAD

**Issue by GeiseSaunier** [GeiseSaunier/Autizando#6]
**Descrição**
A ideia dessa issue é desenvolver a página destinada a recuperação de senha do usuário.

**Objetivo**
Desenvolver a página de recuperação de senha.

**Tarefas**
- [x] Criar componente para a página de recuperação de senha;
- [x] Inserir especificações para a página de recuperação de senha;

**Checklist**
- [x] Componentes criados;
- [x] Especificações inseridas;

**Critérios de aceitação**
- [x] A equipe está de acordo com as implementações;

**Comment by GeiseSaunier** [comment]
@IanoMaciel você pode revisar a tela de recuperação de senha e em seguida fechar a nossas issue?

**Comment by IanoMaciel** [comment]
@GeiseSaunier, ok!

**Comment by IanoMaciel** [comment]
Issue finalizada.
